Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-24.04"
    vm1.vm.network  "public_network", bridge: "wlp3s0"
    vm1.vm.synced_folder  "../shared/vm1", "/vagrant_data"
    vm1.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y apache2
      SHELL
  end

    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "generic/debian12"
      vm2.vm.network  "private_network", bridge: "wlp3s0", ip: "192.168.56.2"
      vm2.vm.synced_folder  "../shared/vm2", "/vagrant_data"
      vm2.vm.provision "shell", inline: <<-SHELL
          echo $(date) >> time.txt
        SHELL
    end

    config.vm.define "vm3" do |vm3|
          vm3.vm.box = "bento/ubuntu-24.04"
          vm3.vm.network  "public_network", bridge: "wlp3s0", ip: "192.168.31.254"
          vm3.vm.synced_folder  "../shared/vm3", "/vagrant_data"
    end

end
